### ISSUE TITLE
Normal function and method receiver should be able to be different.

### ISSUE THREAD

**Issue by marcelloh** [nikolaydubina/smrcptr#7]
If I have :
```
func NewCountryRepository(dbConn *db.DBConn) (*CountryRepository, error) {
   ....
}
```
and 
```
func (repo CountryRepository) GetMoreRecordsJSON(_ map[string][]string) (data []byte, err error) {
   ....
}
```
1.40  states that NewCountryRepository uses a pointer and all others use a value.
(All others have a method receiver too.)

So I think in this case, the NewCountryRepository has no method receiver and therefor should not be mentioned.
(I think the version before 1.3.2 didn't mention this.)

**Comment by nikolaydubina** [comment]
I would keep old behavior with it disabled, but need to show "default" value on how to select constructors, so might as well just put it into default value of that CLI arg.

**Comment by marcelloh** [comment]
Ok, fair enough, as long as I can influence this.
I didn't see this solution on the Readme hint, hint ;-)

Great tool btw.

**Comment by marcelloh** [comment]
btw: you made a typo:
smrcptr -constructor="" ./...
this works :-)

**Comment by nikolaydubina** [comment]
:+1:

tbh, it was poor choice naming this linter. may switch to something better in future... (of course will try to minimize disruption. will archive old repository and add readme + go mod directive for deprecation like `// Deprecated: use example.com/mod/v2 instead.`).
